<?php
/**
 * @file
 * Main procedural code file for the Bounce Processing module.
 */

/**
 * Implements hook_mail_alter().
 */
function bounce_processing_mail_alter(&$message) {
  // This hook modifies the Return-Path value to include the recipient's
  // address. The technique is called Variable Envelope Return Path (VERP) and
  // enables easy identification of the intended recipient for incoming bounce
  // messages. That identification happens in MessageAnalyzer classes, e.g.
  // SimpleDSNClassifier.
  // @todo Make Return-Path base address configurable.
  // @todo Maybe also make VERP optional.

  // Identify current Return-Path value.
  $site_mail = \Drupal::config('system.settings')->get('site.mail');
  $return_path = $message['headers']['Return-Path'];
  if ($site_mail != $return_path) {
    // Return-Path has been altered already, let's bail.
    return;
  }

  // Include recipient address in Return-Path value.
  // @todo Handle multiple recipients and "Foo <a@b.c>" format.
  if ($return_path) {
    $to = str_replace('@', '=', $message['to']);
    $message['headers']['Return-Path'] = preg_replace('/@/', "+$to@", $return_path);
  }
}
