# Module settings
inmail.settings:
  label: 'Inmail settings'
  type: config_object
  mapping:
    return_path:
      label: 'Return-Path address'
      type: email
    log_raw_emails:
      label: 'Log raw email messages'
      type: boolean
    batch_size:
      label: 'Batch size'
      type: integer

# Config entities
inmail.analyzer.*:
  label: 'Message analyzer'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.plugin.analyzer.[%parent.plugin]
    weight:
      label: 'Weight'
      type: integer

inmail.handler.*:
  label: 'Message handler'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.plugin.handler.[%parent.plugin]

inmail.deliverer.*:
  label: 'Mail deliverer'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.plugin.deliverer.[%parent.plugin]
    message_report:
      label: 'Message report'
      type: boolean

# Empty default configuration schema
inmail.plugin.analyzer.*:
  label: 'Analyzer configuration'
  type: mapping

inmail.plugin.handler.*:
  label: 'Handler configuration'
  type: mapping

inmail.plugin.deliverer.*:
  label: 'Deliverer configuration'
  type: mapping
  mapping:
    config_id:
      label: 'Config ID'
      type: string

# Specific analyzer/handler configuration
inmail.plugin.handler.moderator_forward:
  label: 'Moderator Forward handler configuration'
  type: mapping
  mapping:
    moderator:
      label: 'Moderator address'
      type: email

inmail.plugin.deliverer.imap:
  label: 'IMAP Deliverer'
  type: inmail.plugin.deliverer.*
  mapping:
    host:
      label: 'Host'
      type: string
    ssl:
      label: 'SSL'
      type: boolean
    novalidate_ssl:
      label: 'Novalidate-cert'
      type: string
    protocol:
      select: 'Protocol'
      type: string
    imap_port:
      label: 'IMAP port'
      type: integer
    pop3_port:
      label: 'POP3 port'
      type: integer
    username:
      label: 'Username'
      type: string
    password:
      label: 'Password'
      type: string
    delete_processed:
      label: 'Delete processed'
      type: boolean

# Schema for IMAP quota sensor.
monitoring.settings.inmail_monitoring_imap_quota:
  type: monitoring.settings_base
  label: 'IMAP quota sensor settings'
  mapping:
    imap_fetcher:
      label: Inmail IMAP fetcher to track its quota
      type: string

# Schema for monitoring sensors.
monitoring.settings.inmail_incoming_mails:
  type: monitoring.settings_base
  label: 'Inmail sensor settings'
  mapping:
    deliverers:
      label: Deliverers to track the incoming mails
      type: sequence
      sequence:
        type: string
        label: 'Deliverer'
    count_type:
      label: Mails to count
      type: string
