# Module settings
inmail.settings:
  label: 'Inmail settings'
  type: mapping
  mapping:
    return_path:
      label: 'Return-Path address'
      type: email

# Config entities
inmail.inmail_analyzer.*:
  label: 'Message analyzer'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.analyzer.[%parent.plugin]
    weight:
      label: 'Weight'
      type: integer

inmail.inmail_handler.*:
  label: 'Message handler'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.handler.[%parent.plugin]

inmail.deliverer.*:
  label: 'Mail deliverer'
  type: config_entity
  mapping:
    id:
      label: 'Machine-name'
      type: string
    label:
      label: 'Label'
      type: label
    plugin:
      label: 'Plugin'
      type: string
    configuration:
      label: 'Configuration'
      type: inmail.plugin.deliverer.[%parent.plugin]

# Empty default configuration schema
inmail.analyzer.*:
  label: 'Analyzer configuration'
  type: mapping

inmail.handler.*:
  label: 'Handler configuration'
  type: mapping

# Specific plugin configuration
inmail.handler.moderator_forward:
  label: 'Moderator Forward handler configuration'
  type: mapping
  mapping:
    moderator:
      label: 'Moderator address'
      type: email

inmail.plugin.deliverer.imap:
  label: 'IMAP Deliverer'
  type: mapping
  mapping:
    host:
      label: 'Host'
      type: string
    ssl:
      label: 'SSL'
      type: boolean
    port:
      label: 'Port'
      type: integer
    username:
      label: 'Username'
      type: string
    password:
      label: 'Password'
      type: string
    batch_size:
      label: 'Batch size'
      type: integer
