<?php
/**
 * @file
 * Procedural code for the Bounce Processing PHPMailer-BMH submodule.
 */

use Drupal\bounce_processing\Message;

if (!function_exists('imap_rfc822_parse_adrlist')) {
  /**
   * Parses the address string as defined in RFC 2822 and for each address.
   *
   * This function is used in bmhDSNRules(). To avoid having to depend on the
   * IMAP extension just for this, this defines an alternative address parser.
   *
   * @see http://php.net/manual/en/function.imap-rfc822-parse-adrlist.php
   */
  function imap_rfc822_parse_adrlist($address, $default_host) {
    // For each address.
    return array_map(function($address) {
      // Split the address and put the parts in an object, in order to match the
      // return value structure of the original function.
      list($mailbox, $host) = explode('@', $address);
      return (object) ['mailbox' => $mailbox, 'host' => $host];
    }, Message::parseAddress($address));
  }
}
